server:
  port: 8083

spring:
  application:
    name: movement-service

  config:
    import: optional:configserver:http://config-server:8888

  data:
    mongodb:
      uri: mongodb://host.docker.internal:27017/movement-database

  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: movement-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: '*'
            value:
              default:
                type: com.bank.ayrton.movement_service.dto.BootcoinTransactionEvent
    listener:
      ack-mode: record

  redis:
    host: host.docker.internal
    port: 6379

eureka:
  client:
    service-url:
      defaultZone: http://host.docker.internal:8761/eureka
    register-with-eureka: true
    fetch-registry: true