server:
  port: 8083

spring:
  application:
    name: movement-service
  config:
    import: optional:configserver:http://localhost:8888
  data:
    mongodb:
      uri: mongodb://localhost:27017/movement-database
  kafka:
    bootstrap-servers: localhost:9092 #direccion del broker
    consumer:
      group-id: movement-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer #los eventos son mopeados ocmo objetos
      properties:
        spring.json.trusted.packages: '*'
    listener:
      ack-mode: record
  redis:
    host: localhost
    port: 6379