server:
  port: 8083

spring:
  application:
    name: movement-service
  config:
    import: optional:configserver:http://localhost:8888
  data:
    mongodb:
      uri: mongodb://localhost:27017/movement-database
  kafka:
    bootstrap-servers: localhost:9092